version: '3.8'

services:
  app1: &app_instance
    build: .
    container_name: app1
    environment:
      - PORT=8080
    env_file:
      - .env
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  app2:
    <<: *app_instance
    container_name: app2
    environment:
      - PORT=8080
    env_file:
      - .env
    ports:
      - "8082:8080"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

  nginx:
    image: nginx:1.23-alpine
    container_name: 1b
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - app1
    - app2
    ports: 
    - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
      
volumes:
  postgres-data:
