CREATE TABLE IF NOT EXISTS Client (
    id INT PRIMARY KEY,
    limite INT NOT NULL,
    saldo INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Transaction (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    clientId INT NOT NULL,
    tipo CHAR(1) NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    descricao CHAR(10) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (clientId) REFERENCES Client(id)
);

INSERT INTO Client (id, limite, saldo) VALUES (1, 100000, 0),(2, 80000, 0),(3, 1000000, 0),(4, 10000000, 0),(5, 500000, 0) ON CONFLICT (id) DO NOTHING;